services:

  mongo:
    volumes:
      - /home/chris/mongo:/data/db

  modbus_app:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]