services:

  mongo:
    volumes:
      - /home/chris/mongo:/data/db
    command: --quiet

  web_app:
    image: cv43nyu/allippe:web
    volumes:
      - /home/chris/logs/web:/app/logs
    deploy:
      resources:
        limits:
          memory: 8G

  modbus_app:
    image: modbus:1.0
    volumes:
      - /home/chris/logs/modbus:/app/logs
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
