services:

  mongo:
    volumes:
      - /home/chris/mongo:/data/db

  web_app:
    image: cv43nyu/allippe:web

  modbus_app:
    image: cv43nyu/allippe:modbus
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
