services:

  mongo:
    build:
      context: ..
      dockerfile: ./docker/mongo.Dockerfile
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"